name: Presubmit
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        fail_on_error: true
        github_token: ${{ secrets.GITHUB_TOKEN }}