name: Presubmit
on:
  push:
  pull_request:

jobs:
  lint-pr:
    name: PR Linter
    if: ${{ github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        fail_on_error: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    name: Commit Linter
    if: ${{ !github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: chipsalliance/verible-linter-action@main
      with:
        reviewdog_reporter: github-check
        fail_on_error: true
        github_token: ${{ secrets.GITHUB_TOKEN }}